# Generated by Django 4.1.1 on 2022-09-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_detail',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
