# Generated by Django 4.1.1 on 2022-10-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_slug_project_detail_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_detail',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project_detail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project_detail',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project_detail',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='project_detail',
            name='slug',
        ),
    ]
