# Generated by Django 4.1.1 on 2022-10-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_project_detail_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_detail',
            name='url_link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
