# Generated by Django 4.1.1 on 2022-10-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_detail_url_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_detail',
            name='url_link',
        ),
    ]
