# Generated by Django 4.1.1 on 2022-10-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_project_detail_url_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_detail',
            name='url_link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
