# Generated by Django 4.1.1 on 2022-10-03 14:06

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_detail_url_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_detail',
            name='image1',
            field=models.ImageField(default='', upload_to=main.models.image_upload_detail1),
            preserve_default=False,
        ),
    ]
