# Generated by Django 4.1.1 on 2022-10-03 14:07

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_detail_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_detail',
            name='image1',
            field=models.ImageField(null=True, upload_to=main.models.image_upload_detail1),
        ),
    ]
